### ISSUE TITLE
Capture Merchant Feedback within Plugin

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1211]
# Initial Discovery Conversation
https://rtcamp.slack.com/archives/GA2P84GBZ/p1560884054014300
**Documentation:** https://wisdomplugin.com/support/#getting-started

# Phase 1 Acceptance Criteria
- [x] Create Account with Wisdom
- [x] Ensure it is WP VIP Compatible
- [x] Evaluate to ensure that it solves our need and has a good UX
- Make the following configurations:
  - [x] Set `Include deactivation form` = `TRUE`
  - [x] Set `Notification message` = `Option 0`
  - [x] If possible also include `Sandbox Merchant ID` & `Live Merchant ID` in the tracked data so that we can join this information to our other data points. It appears that we could potentially use `plugin_options` or  `plugin_options_fields` to hold this data (See Available Parameters [here](https://wisdomplugin.com/support/#extending-wisdom)).
- [ ] Get approval from WP VIP

**Potential Enhancements for Future Phases**
- ~~Deactivation survey is not available if plugin is deactivated from Advanced Tab~~ #1221
- ~~Other Plugins do not appear to export to CSV properly (only one plugin is listed per site)~~ 
_This works properly, they are just delimited by line breaks._
- ~~Allow merchants to Opt in or Out after Activation on the LaterPay Settings Page ([here](https://wisdomplugin.com/support/#advanced))~~ #1220 
- Make a way to make Wisdom think that we have never used it on a site before (for testing purposes)

**Comment by ksmoore125** [comment]
@thrijith - Now that I understand that we do not receive the admin email without their opt-in I would like to adjust this as follows:

`Notification message` = `Option 2`
**For the first message, we can use their default message:**
> Thank you for installing our product. We would like to track its usage on your site. We don’t record any sensitive data, only information regarding the WordPress environment and product settings, which we will use to help us make improvements to the product. Tracking is completely optional.

**For the second message can we customize it to the following?**
> Thank you for opting in to tracking! May we contact you to provide updates or request feedback?

**Comment by thrijith** [comment]
Released in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
