### ISSUE TITLE
Add filters to the dashboard

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#446]
The merchant should be able to choose from several **intervals** for the dashboard. The data should then be calculated and displayed for the respective interval:

- 1 day
- 1 week (+1 day)
- 2 weeks (+1 day)
- 1 month (+1 day)

For the **1 day** option, we should provide data on an **hourly** basis, starting with "**today**".
For all other options, we should provide data on a **daily** basis. The last date that should be available should be "**yesterday**", because "**today**" (as an incomplete day) would not provide comparable data. 

There should also be an option to filter the **revenue model**.
- all
- PPU
- SIS

Lastly, the merchant should be able to **jump to different intervals** of the selected time range (i.e. step one day | week | fortnight | month back or forward.

---------------------

## TODO's ##

* [x] adding time intervals
* [x] adding time ranges 
* [x] adding filter for **revenue model**

**Comment by Chrico** [comment]
Time intervals are already implemented. Next will be the *time ranges* and *filters*

**Comment by Chrico** [comment]
@drdla is the __monthly__ interval:

* "complete last month" -> for 12.01.2015 -> complete December 2014
* or "yesterday - 30 days" -> for 12.01.2015 -> 06.12.2015 - 11.01.2015

Same for __weekly__ and __2-weeks__ : "yesterday - 8/14 days" or "current week - 1/2"?

Second question: What about implementing a dropdown with all available stats? This should be easier to navigate than clicking n-times back. Also we could add select2 to enable searching (on "daily" interval, we could have >360 options). Something like this:

__monthly__
![image](https://cloud.githubusercontent.com/assets/3417446/5703686/19c143e2-9a6a-11e4-9bed-334e9f237b6e.png)


__weekly__
or 
* 04.01.14 - 11.01.14
* 03.01.14 - 10.01.14
* 02.01.14 - 09.01.14
* 01.01.14 - 08.01.14
* ...
![image](https://cloud.githubusercontent.com/assets/3417446/5703709/4efe0e8c-9a6a-11e4-806a-9d9f29d506e7.png)

**Comment by drdla** [comment]
The intervals are 14 days and 30 days.

**Comment by drdla** [comment]
The specified implementation for selecting an interval is based on the assumption that people want to compare a given interval to the previous one and not compare to an interval a long time ago.
If this assumption holds true, the back / forward links allow switching the interval in one click, whereas a select requires two clicks.
If the assumption is wrong, your suggestion would make more sense.

Generally speaking, I would vote for the solution that requires less implementation effort.

**Comment by Chrico** [comment]
@drdla 
Yep thats right. A select requires two clicks, but will show more possibilities and a faster navigation back / forward when jumping through several reports. 

E.g.: Today's report is `04.01.14 - 12.01.14` but i want to compare the  `first week of Januar 2015` with the `last week of December 2014`.

The back / forward links would make it more difficulty to navigation a larger time period back (more clicks and loading). Also you can't see "the end" - when was the first report? 

The monthly report based on `{month} {year}` intead of `{yesterday-30days} - {yesterday}` would give the user more changes when navigating back. Currently it will show following:

```
"12.12.14 - 12.01.15" 
-> naviagte "back" 
---> "11.12.2014 - 11.01.15"
```

The changes in our diagrams are minimalistic, because only 2 days are changing. A monthly interval based on the complete month would give more changes to compare:

```
Janurary 2015
-> navigate "back"
--> December 2014
```

On this assumption we would have following back / forward navigations:

* daily -> 12.01.2015 -> "back" -> 11.01.2015
* weekly -> KW 02 2015 -> "back" -> KW 01 2015
* 2-week -> KW 01 2015 - KW 02 2015 -> "back" -> KW 12 2014 - KW 01 2015
* monthly -> December 2014 -> "back" -> November 2014

Maybe it would be also nice to have a look at other Analytics-Tools ( [Piwik Demo](https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=month&date=2015-01-11#/module=Dashboard&action=embeddedIndex&idSite=7&period=month&date=2015-01-11&idDashboard=1) ). What about a calendar?

![image](https://cloud.githubusercontent.com/assets/3417446/5716719/18351956-9af4-11e4-932f-95cea2a1400c.png)

**Comment by drdla** [comment]
Suggestion: Why don't we allow 1 day, 1 week, 8 days, 2 weeks, 30 days, 1 month?
It's not like there is a limit on the options we can offer and the implementation is trivial.
I don't want to introduce complex date selection or comparisons now. We can always add that later.
In the first step I want to have the possibility to change the shown interval and other features like details per item. After that we can always further enhance the date selection options.

**Comment by Chrico** [comment]
@drdla 
Ok. The timeRange-select is now implemented as defined:

![image](https://cloud.githubusercontent.com/assets/3417446/5720965/c733ed88-9b2b-11e4-8082-ae0fa51070d3.png)

Currently, i can't access the correct data for PPU/SIS. The flag is not saved when purchasing a post.

**Comment by Chrico** [comment]
This is finished and released with LaterPay 0.9.10.
