### ISSUE TITLE
Sales dashboard

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#86]
![screenshot 2014-10-10 13 48 05](https://cloud.githubusercontent.com/assets/135148/4591879/57ceb3d6-5073-11e4-8f90-e8388375e028.png)
## Structure

The dashboard is structured like a classic sales funnel:
**Conversion** -> **Items sold** -> **Revenue**

For each of the three phases, it has
a) a large diagram
b) a few KPIs (key performance indicators), and
c) a list of the 10 best performing items + a list of the 10 worst performing items
## Calculation / Updating of Data

For performance reasons, the dashboard data should be calculated periodically (depending on how heavy the calculation really is - maybe every 6 hours?) and cached, with the option to re-calculate the data by clicking a button ('Compute current data').
## Intervals

By default, all data shown are based on the last 8 days.
The number is 8, because there usually is a pattern within an interval (e.g. Monday is always strong, then it declines until Friday, but Saturday and Sunday is strong again), which requires to have the current day of the week one week ago to assess the current day's value in a meaningful way.

See #446
## KPIs

All KPIs are based on the selected interval!
- ~~**Impressions** - number of page views of posts that are purchasable. Given as number with no decimal place.~~
- **Impressions** - number of page views of posts that are purchasable in the reporting period. Given as number with no decimal place.
- ~~**Conversion** - number of purchased items / _Impressions_. Given as percentage with one decimal place.~~
- **Conversion** - number of purchased items in the reporting period / _Impressions_. Given as percentage with one decimal place.
- ~~**New Customers** - number of users (devices) that purchased for the first time / number of users (devices) that had already purchased before. Given as percentage with no decimal place.~~
- **New Customers** - number of users (devices), who purchased for the first time in the reporting period / number of all users, who purchased in the reporting period. Given as percentage with no decimal place.
- ~~**AVG Items Sold** - todo: define metric. Given as number with one decimal place.~~ 
- **AVG Items Sold** - number of all items sold in the reporting / days in the reporting period
- ~~**Total Items Sold** - number of purchased items. Given as number with no decimal place.~~
- **Total Items Sold** - number of purchased items in the reporting period. Given as number with no decimal place.
- ~~**AVG Purchase** - _Total Items Sold_ / days in the reporting period. Given as number with two decimal places.~~
- **AVG Purchase** - _Total Items Sold_ / _Total Revenue_. Given as number with two decimal places.
- ~~**Total Revenue** - sum of prices of purchased items. Given as number with two decimal places.~~
- **Total Revenue** - sum of prices of purchased items in the reporting period. Given as number with two decimal places.
## Diagrams

**Conversion** - shows the average _Conversion_ of all items for every day of the selected interval.
**Items Sold** - shows the total number of _Items Sold_ of all items for every day of the selected interval.
**Revenue** - shows the total revenue of all items for every day of the selected interval.

The data for the diagrams have to be provided in the following structure:
x-axis ticks (used by all diagrams):

```
[[1, day-of-week-1], [2, day-of-week-2], [3, day-of-week-3], [4, day-of-week-4], [5, day-of-week-5], [6, day-of-week-6], [7, day-of-week-7], [8, day-of-week-8] ]
```

diagram data:

```
[[1, kpi-value-1], [2, kpi-value-2], [3, kpi-value-3], [4, kpi-value-4], [5, kpi-value-5], [6, kpi-value-6], [7, kpi-value-7], [8, kpi-value-8] ]
```
## Top / Bottom Items Lists

For each phase, there are two lists: one listing the 10 best performing items and a second one listing the 10 worst performing items in that category.
Each list item is composed of
- its title
- its value (most relevant KPI, i.e. conversion rate, sales, revenue)
- a sparkline (bar chart) of its value on a daily basis for the last 8 days

---
# TODO's
- [x] Return the percentage values as integers: 0.02 -> 2
- [x] start date (date of first day in interval) and
- [x] end date (date of last day in interval)
- [x] complete rendering of diagrams
- [ ] **Note**: Will be done in #446 | implement all options in heading (selecting interval, selecting revenue model, skipping to next / prev result set)
- [x] always render 8 days in sparklines of top / bottom lists
